Update patch set 20
Patch Set 20:

> Patch Set 20: Verified-1
> 
> Build Failed 
> 
> https://jenkins.acumos.org/job/documentation-rtd-verify-master/4086/ : FAILURE
> 
> Logs: https://logs.acumos.org/production/vex-yul-acumos-jenkins-1/documentation-rtd-verify-master/4086
> 
> https://jenkins.acumos.org/job/license-usage-manager-maven-javadoc-verify-master-openjdk8/30/ : SUCCESS
> 
> Logs: https://logs.acumos.org/production/vex-yul-acumos-jenkins-1/license-usage-manager-maven-javadoc-verify-master-openjdk8/30
> 
> https://jenkins.acumos.org/job/license-usage-manager-maven-dl-verify-master-mvn35-openjdk8/31/ : SUCCESS
> 
> Logs: https://logs.acumos.org/production/vex-yul-acumos-jenkins-1/license-usage-manager-maven-dl-verify-master-mvn35-openjdk8/31

Does anybody know whether the following ERROR in the log is the reason for this failure ?
found in https://logs.acumos.org/production/vex-yul-acumos-jenkins-1/documentation-rtd-verify-master/4086/console.log.gz 

[documentation-rtd-verify-master] $ /bin/bash -l /tmp/jenkins8111823384299218998.sh
---> tox-install.sh
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Package 'more-itertools' requires a different Python: 2.7.5 not in '>=3.4'
Build step 'Execute shell' marked build as failure

Patch-set: 20